### ISSUE TITLE
Book_2_Ch_00__正文前_page 1

### ISSUE THREAD

**Issue by Maze-is-moon** [Visualize-ML/Book2_Beauty-of-Data-Visualization#10]
用词优化的小建议，如图。
<img width="712" alt="image" src="https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/139441233/e27ccabd-4416-4d48-adcb-09a65a136ce4">

**Comment by Visualize-ML** [comment]
谢谢你，针，确实更舒服。请继续批评指正。

Cheers,
James
