### ISSUE TITLE
Bk2_Ch13_极坐标——13.1 线图

### ISSUE THREAD

**Issue by hsplsp** [Visualize-ML/Book2_Beauty-of-Data-Visualization#13]
![屏幕截图 2023-08-22 095343](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/119094347/c293e749-f64c-4f25-8138-c9ada3180276)

这里“XX绘制更多的极坐标线图”显示未找到引用源

**Comment by Visualize-ML** [comment]
谢谢你，十月份统一修改上传。请继续批评指正。

Cheers,
