### ISSUE TITLE
Bk_2_Ch_04__装饰的pdf中存在内容错误

### ISSUE THREAD

**Issue by shuihaojiao** [Visualize-ML/Book2_Beauty-of-Data-Visualization#15]
page 5
![image](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/79622848/ad57b681-a5f3-456a-aa15-cf2d657aa3fa)
这里书写的代码应该是以下内容：
ax.set_xlim(-4,4); ax.set_ylim(-0.5, 0.5); 
ax.axis('off')

**Comment by shuihaojiao** [comment]
page 8
![image](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/79622848/8e44a713-da6d-4e4d-9a7c-689277a53e9e)
这里书写的代码应该是以下内容：
ax.set_xlim(-15,15); ax.set_ylim(-1.5, 1.5); 
ax.axes.get_xaxis().set_visible(False)
ax.axes.get_yaxis().set_visible(False)

**Comment by Visualize-ML** [comment]
谢谢你，确实贴错了。这个issue先开着，下个月统一修改。情继续批评指正。

**Comment by hxy2321548628** [comment]
![Screenshot from 2023-12-11 09-58-59](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/149643090/980fdd24-918f-44ba-9d23-fd3e37f747c7)
图片高亮显示的地方应该是ax.yaxis.set_minor_locator(minor_locator)
