### ISSUE TITLE
Book_2_CH_04  在4.1节正文单词错误

### ISSUE THREAD

**Issue by Harden-code** [Visualize-ML/Book2_Beauty-of-Data-Visualization#16]
![1704676420311](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/77663001/1836d3c5-bbdb-4fed-a28e-eb8f30449cdf)
图脊 spine

**Comment by Visualize-ML** [comment]
谢谢你，请继续批评指正。

**Comment by Visualize-ML** [comment]
谢谢你，也请你继续批评指正。

Cheers,
