### ISSUE TITLE
BK_2_Ch06_06.ipynb 代码疑虑

### ISSUE THREAD

**Issue by Harden-code** [Visualize-ML/Book2_Beauty-of-Data-Visualization#17]
老师 在这个visualize_cm_in_RGB方法里，这段代码list_colors_RGB = [colors.to_rgb(rgb_idx) for rgb_idx in list_colors]，list_colors感觉对新手不是特别友好，这引用的是全局作用域里的变量，感觉把它定义成参数会好理解一点

**Comment by Visualize-ML** [comment]
谢谢你，确实；当时，写自定义函数时，没注意到；请继续批评指正。
