### ISSUE TITLE
代码疑虑

### ISSUE THREAD

**Issue by githubyangkai** [Visualize-ML/Book2_Beauty-of-Data-Visualization#18]
![PixPin_2024-04-06_16-46-55](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/121996502/39550cc3-19bb-406d-ae9e-c2ca8691adba)
Normalize对象创建的归一化值normalized_values并没有直接用在sns.heatmap函数中。在您的代码中，random_values.reshape(-1, 1)是传递给heatmap函数的数据，而这个数据并没有经过归一化处理。

**Comment by Visualize-ML** [comment]
谢谢你，这一处确实需要修改。请继续批评指正。
