### ISSUE TITLE
Ch_24的PDF，Page10图的标注错误

### ISSUE THREAD

**Issue by chenqiuhao** [Visualize-ML/Book2_Beauty-of-Data-Visualization#19]
Book_2_Ch_24_复数__可视之美__鸢尾花书__从加减乘除到机器学习.pdf文件Page10，公式忘记乘2了，代码里乘了2.
![image](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/28197390/df855ea8-a54d-4708-8fe1-47605769a9dd)
![image](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/28197390/96709c7d-7722-41a8-9f0d-ddb3465575dc)

**Comment by Visualize-ML** [comment]
谢谢你，确实少乘了2；请继续批评指正
