### ISSUE TITLE
book1在哪

### ISSUE THREAD

**Issue by 123far** [Visualize-ML/Book2_Beauty-of-Data-Visualization#2]

**Comment by AbandonKey** [comment]
我也想问

**Comment by 123far** [comment]
你好，我是就业实践部 朱皓宇，已收到你的来信。我会及时查收并回复，若有急事，请联系：18203086014

**Comment by Visualize-ML** [comment]
最近专注整理《可视之美》。大家稍等一下，第一本争取4月末、5月初上传

**Comment by 123far** [comment]
你好，我是就业实践部 朱皓宇，已收到你的来信。我会及时查收并回复，若有急事，请联系：18203086014
