### ISSUE TITLE
Ch28 SVD图疑问

### ISSUE THREAD

**Issue by chenqiuhao** [Visualize-ML/Book2_Beauty-of-Data-Visualization#20]
V^T是逆时针旋转45度，图上画的是顺时针旋转45度，是不是画错了。
![image](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/28197390/0f2e6bee-f256-49e7-badf-27ad67740fc2)

**Comment by Visualize-ML** [comment]
谢谢你！你发现了这幅图的一个秘密。我非常建议你沿着这个思路一下，为什么图中SVD分解结果，和代码分解结果不同。导致这种差异的原因是什么？此外，即便SVD分解结果不同，最后 U @ S @ V.T的结果又一致？
