### ISSUE TITLE
Bk_2_Ch03_06.ipynb 冗余代码

### ISSUE THREAD

**Issue by OrezzerO** [Visualize-ML/Book2_Beauty-of-Data-Visualization#22]
https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/blob/f1ff7b6d9010e45d7ffa7fad284bd58ff657bb4a/Book2_Ch03_Python_Codes/Bk_2_Ch03_06.ipynb#L81

ax1 没有设置 ylable , 在这里设置 `set_label_position` 没有什么用, 应该是冗余代码, 可以去掉. 

另外问下, 这个项目接受 PR 吗? 有需要我可以提PR修复

**Comment by Visualize-ML** [comment]
谢谢你，确实冗余。开issue就好，我会在后续统一修改。请继续批评指正。
