### ISSUE TITLE
分享: 找不到 Roboto 字体解决方案

### ISSUE THREAD

**Issue by OrezzerO** [Visualize-ML/Book2_Beauty-of-Data-Visualization#23]
## 现象
运行代码会遇到告警: 
```
findfont: Generic family 'sans-serif' not found because none of the following families were found: Roboto
```

系统安装 Roboto 之后依然无法解决. 

## 解决方案 
> 基于 osx 系统, windows 系统未尝试. 方案非官方, 个人感觉比较 hack ,如果有更好的,欢迎指正. 

### 1. 找到 matplotlib 库所在位置  
通过 matplotlib? 查看 matplotlib 库安装位置:
```
Type:        module
String form: <module 'matplotlib' from '/Users/zhangchengxi/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py'>
File:        ~/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py
Docstring: 
```

### 2. 找到字体 ttf 文件夹: 
切换到第一步找到的 matplotlib 库位置, 比如我的是 `~/anaconda3/lib/python3.11/site-packages/matplotlib/`, 找到子文件夹 `ttf`
比如我的是 `~/anaconda3/lib/python3.11/site-packages/matplotlib/mpl-data/fonts/ttf`

### 3. 复制 Roboto 相关 ttf 文件到这个文件夹 
复制 Roboto 相关 ttf 文件到这个文件夹 , 并重启 jupyter

**Comment by Visualize-ML** [comment]
谢谢你，确实是个好hack。请继续批评指正。
