### ISSUE TITLE
32.4 重心坐标系 重心坐标系定义相关讨论

### ISSUE THREAD

**Issue by OrezzerO** [Visualize-ML/Book2_Beauty-of-Data-Visualization#24]
看 32.4 重心坐标系 有点费劲, 开个 Issue 讨论讨论. 

##  问题1 
> 从物理角度来看,重心坐标系 (barycentric coordinate system) 是一种描述一个几何形状内部任意点位置的方法。它是以该形状的重心作为原点建立的坐标系。

这句话里,我没有理解原点的含义, 刚开始看的时候, 我以为是坐标系中 (0,0,0) 所在的位置就是原点. 但后面才知道, 重心坐标系中不包含 (0,0,0)这个点.  重心所在点是 (1/3,1/3,1/3)

## 问题2
> 在平面上的一个三角形中,任何一点都可以表示为三个定点的加权平均值,其中每个定点的权重由它到该点的距离与该三角形的周长之比确定。这些权重称为该点在三角形的重心坐标。

首先, "定点" 含义不是很明确, 说是三角形三个 "顶点" 是否更合适? 

这里我没有理解权重和周长的关系. 
我带入了三角形 A(0,1) , B (0,0), C (1,0) 进入这句话: 

在平面上的一个三角形 A(0,1) , B (0,0), C (1,0)  中, 有一个点 P(x,y) 都可以表示为三个顶点的加权平均值 . 其中每个顶点的权重由它(顶点)到该点(P)的距离与该三角形的周长之比确定(如何确定, 是什么公式?)。这些权重称为该点在三角形的重心坐标。

`在平面上的一个三角形 A(0,1) , B (0,0), C (1,0)  中, 有一个点 P(x,y) 都可以表示为三个顶点的加权平均值 ` 这句话用数学语言表示出来, 可能会更好理解一些:  
```
P=λ1​A+λ2​B+λ3​C
```
那么 P 的重心坐标就是 (λ1​,λ2,λ3).

带入三个顶点 A (1,0,0) B(0,1,0) C(0,0,1) 是能对应起来的. 

接着我用 `其中每个顶点的权重由它(顶点)到该点(P)的距离与该三角形的周长之比确定` 验证. 
假设 P 为 (0,1) 
三角形周长为 2+根号2
P 到点A 的距离为 0 ,  比值为 0 
P 到点B 的距离为 1 , 比值为  1/( 2+根号2 )
P 带点C 的距离为 根号2 ,比值为  根号2/( 2+根号2 ) 

实际上 A 的质心坐标为 (1,0,0) 和上面的比值看上去没什么关系.

**Comment by OrezzerO** [comment]
贴一下我和 GPT 的讨论: 
问: 
> "在平面上的一个三角形中,任何一点都可以表示为三个定点的加权平均值,其中每个定点的权重由它到该点的距离与该三角形的周长之比确定。这些权重称为该点在三角形的重心坐标。" 详细说说 重心坐标和周长有什么关系

回答: 
<img width="761" alt="image" src="https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/13081689/2174f6ac-f6e4-482f-9659-86167da810d9">
<img width="784" alt="image" src="https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/13081689/b81dce09-359a-4e28-aef7-21b8a317d70c">

**Comment by Visualize-ML** [comment]
谢谢你，确实有描述不准确的地方。这个issue先开着。我会专门查一下。

矩阵运算来坐标转换是没问题的，里面确实用到了面积。
