### ISSUE TITLE
Book2_ch_03  图6 

### ISSUE THREAD

**Issue by suterberg** [Visualize-ML/Book2_Beauty-of-Data-Visualization#26]
图6的第一张子图，坐标标识有点问题，还有就是3.4是没有源码么，要自己敲？

**Comment by Visualize-ML** [comment]
麻烦请具体指出问题，谢谢

**Comment by suterberg** [comment]
![捕获](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/32859414/21249d6c-4fe5-4b0b-af1f-9b28bd06a613)
左侧定位线和右侧一样
![捕获](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/32859414/e32c193a-33a4-421b-90f9-f9acea7096b3)

**Comment by Visualize-ML** [comment]
谢谢你，纸质书已经修改，电子版草稿不再同步。请继续批评指正。

Cheers
