### ISSUE TITLE
BK_2_Ch09_08.ipynb

### ISSUE THREAD

**Issue by suterberg** [Visualize-ML/Book2_Beauty-of-Data-Visualization#27]
api变更，最新版的matplotlib 删除了 matplotlib.cm.get_cmap 使用 matplotlib.colormaps[name]替代
cmap = mpl.colormaps['RdYlBu']

**Comment by Visualize-ML** [comment]
谢谢你，确实需要根据版本，更新代码。请继续批评指正。
