### ISSUE TITLE
Bk_2_Ch18_06 Bk_2_Ch18_07绘图问题

### ISSUE THREAD

**Issue by Zhang-Baolin** [Visualize-ML/Book2_Beauty-of-Data-Visualization#29]
原代码运行警告
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  f = [[x, y, z]] @ np.linalg.pinv(A @ A.T) @ [[x], [y], [z]]

新numpy版本下，出现了错误
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 1) + inhomogeneous part.

**Comment by Visualize-ML** [comment]
谢谢你，版本问题，需要优化代码。请继续批评指正。
