### ISSUE TITLE
专有名词翻译反馈

### ISSUE THREAD

**Issue by inkydragon** [Visualize-ML/Book2_Beauty-of-Data-Visualization#3]
读起来有些专有名词翻译的比较奇怪，所以来反馈一下。

参考工具
- 术语在线：https://www.termonline.cn/
- CNKI 学术翻译：https://dict.cnki.net/

名词
- Topic 3.4 色谱
	color map => 色彩表/色表/颜色对照表  
	"色谱" 一般专指 chromatography
- Topic 4.5 不同网格 / Page 2 / 面具 (mask)
	mask => 蒙版/遮罩
- Topic 4.7 热图
	heat map => 热力图/热点图

**Comment by Visualize-ML** [comment]
谢谢你的反馈！翻译的时候有考虑这些约定成俗的翻译，但是为了方便“中文-英文”交流，有个别翻译可能会采用“直译”。这一点还要和出版社协商。

欢迎继续批评指正。Cheers,
James
