### ISSUE TITLE
Book_2_Ch_02 P38

### ISSUE THREAD

**Issue by AnikiFan** [Visualize-ML/Book2_Beauty-of-Data-Visualization#30]
![Screenshot 2024-07-31 163709](https://github.com/user-attachments/assets/b50a2c4e-a23e-41f5-ae03-43daae9a04ba)
框中两行应该颠倒了，plotly有交互功能，seaborn没有

**Comment by Visualize-ML** [comment]
确实反了，请继续批评指正，谢谢。
