### ISSUE TITLE
Book_2_Ch_03 insert_axes函数

### ISSUE THREAD

**Issue by AnikiFan** [Visualize-ML/Book2_Beauty-of-Data-Visualization#31]
![Screenshot 2024-07-31 182020](https://github.com/user-attachments/assets/01707051-9f7f-4d0e-b7eb-626834b52295)
不知是否是错误，但是在matplotlib3.8.4中没有该函数，并且在官网上也搜索不到
![Screenshot 2024-07-31 182345](https://github.com/user-attachments/assets/545e3119-bc79-4eab-8d59-43d9ca3565e4)

**Comment by Visualize-ML** [comment]
谢谢你，写错了。
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.inset_axes.html
