### ISSUE TITLE
Book_2_Ch_04__装饰__ Page11 代码部分问题

### ISSUE THREAD

**Issue by AnikiFan** [Visualize-ML/Book2_Beauty-of-Data-Visualization#32]
![Screenshot 2024-07-31 195313](https://github.com/user-attachments/assets/87b45953-252f-4962-b1dc-e4f70d1bb0b9)
红框部分中的两行应该重复了

**Comment by Visualize-ML** [comment]
纸质书已经修改，谢谢你，请继续批评指正。
