### ISSUE TITLE
Book_2_Ch_02__说图__可视之美_Page8

### ISSUE THREAD

**Issue by cyuking** [Visualize-ML/Book2_Beauty-of-Data-Visualization#33]
>gridspec_kw 用于指定子图的网格规格。通过'width_ratios':[3, 1]和
'height_ratios':[1, 3]分别指定了列和行的宽高比。这表示第一列的宽度是第二列的3倍，第一
行的高度是第二行的3倍。

最后一句应该是“第二行的高度是第一行的3倍”。

**Comment by Visualize-ML** [comment]
确实笔误，请继续批评指正。
