### ISSUE TITLE
Book_2_Ch_02__说图__可视之美_Page1

### ISSUE THREAD

**Issue by lang07123** [Visualize-ML/Book2_Beauty-of-Data-Visualization#8]
![图片](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/7733095/c8adc184-f271-4e91-8657-64ed209a47e1)

这些 xxxx 是啥东西...

**Comment by lang07123** [comment]
![图片](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/7733095/918cec81-9e85-4cf2-82f2-6b28b0c39c8c)

Book_2_Ch_03__布局_PAGE 1  也一样

**Comment by Visualize-ML** [comment]
谢谢你，XXXXX都是占位用的，具体内容还没有写好。这本书还要大修大改两次，变化会很大。请继续批评指正。

Cheers,
James
