### ISSUE TITLE
ch01_page17结尾 “我笑他人看不出穿“ 可能多了个出字吧

### ISSUE THREAD

**Issue by wangxiaolong100** [Visualize-ML/Book2_Beauty-of-Data-Visualization#9]
![image](https://github.com/Visualize-ML/Book2_Beauty-of-Data-Visualization/assets/3763994/728759c9-3df1-498c-855b-ac71dca2344a)
上图箭头处

**Comment by Visualize-ML** [comment]
确实多字。请继续批评指正。

Cheers,
James
